name: "nix"

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - "develop"
    paths:
      - "pnpm-lock.yaml"

jobs:
  debugprint:
    runs-on: nix
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "Current working directory: $(pwd)"
          echo "List files: $(ls -al)"
          echo "Environment variables: $(printenv)"
          echo "Environment sops: $SOPS_AGE_KEY_FILE"
          cat $SOPS_AGE_KEY_FILE
